//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGAirlines
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBooking
    {
        public int BookingID { get; set; }
        public string BookingPNR { get; set; }
        public System.DateTime DateOfJourney { get; set; }
        public string FlightStatus { get; set; }
        public string BookingTicketStatus { get; set; }
        public int GuestID { get; set; }
        public int FlightID { get; set; }
    
        public virtual tblFlight tblFlight { get; set; }
        public virtual tblGuest tblGuest { get; set; }
    }
}
